theme: jekyll-theme-slate
title: welcome to shubham's homepage
author:
  name: Shubham Shinde
  email: shinde.shubham85@gmail.com

#description: > # this means to ignore newlines until "show_excerpts:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

social_links:
    twitter: ShindeShubham85
    github:  shindeshu
